
{
    "swagger": "2.0",
    "info": {
        "description": "ルールサービス用機能（生成・削除・設定情報取得）を提供するAPI。",
        "version": "1.0.0",
        "title": "Rule Service Profile"
    },
    "basePath": "/gotapi/ruleService",
    "consumes": ["application/x-www-form-urlencoded", "multipart/form-data"],
    "paths": {
        "/": {
            "get": {
                "summary": "設定されているルールサービス一覧を取得する。",
                "description": "",
                "operationId": "ruleServiceGet",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "description": "サービスID。取得対象スマートデバイス",
                        "required": true,
                        "type": "string"
                    }, 
                    {
                        "name": "ruleServiceId",
                        "in": "query",
                        "description": "ルールを識別するためのサービスID。<br>省略時は全てのルールが取得対象。",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/RuleServiceGetListResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "rules": [
                                    {
                                        "ruleServiceId": "ruleService20170101123456",
                                        "ruleServiceType": "rule",
                                        "triggers": [
                                            {
                                                "triggerInterval": 1000,
                                                "triggerIntervalUnit": "mSec",
                                                "trigger": "/gotapi/deviceOrientation/onDeviceOrientation",
                                                "triggerAction": "PUT",
                                                "triggerParameter": "serviceId=host.localhost.deviceconnect.org&interval=1000",
                                                "comparisonLeft": "orientation.acceleration.x",
                                                "comparisonLeftDataType": "TYPE_JSON",
                                                "comparison": "Excess",
                                                "comparisonRight": "0.55",
                                                "comparisonRightDataType": "TYPE_FLOAT"
                                            }
                                        ],
                                        "operations": [
                                            {
                                                "operationIndex": 1,
                                                "operation": "/gotapi/light",
                                                "operationAction": "POST",
                                                "operationParameter": "serviceId=host.localhost.deviceconnect.org"
                                            }
                                        ]
                                    }
                                ]
                            }
                        }
                    }
                },
                "x-type": "one-shot"
            },
            "post": {
                "summary": "ルールサービスの生成を行う。",
                "description": "",
                "operationId": "ruleServicePost",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "description": "サービスID。取得対象スマートデバイス",
                        "required": true,
                        "type": "string"
                    }, 
                    {
                        "name": "ruleServiceType",
                        "in": "formData",
                        "description": "ルールサービスタイプを設定。<br>省略時はrule。",
                        "required": false,
                        "type": "string",
                        "enum": ["rule", "and"]
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/RuleServiceCreateResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "ruleServiceId": "ruleService20170101123456",
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                },
                "x-type": "one-shot"
            },
            "delete": {
                "summary": "ルールサービスの削除を行う。",
                "description": "",
                "operationId": "ruleServiceDelete",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "description": "サービスID。取得対象スマートデバイス",
                        "required": true,
                        "type": "string"
                    }, 
                    {
                        "name": "ruleServiceId",
                        "in": "query",
                        "description": "削除するルールserviceIdを設定。",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/RuleServiceDeleteResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                },
                "x-type": "one-shot"
            }
        },
        "/errorStatus": {
            "get": {
                "summary": "設定されているルールサービスのエラー発生状況を返す。",
                "description": "",
                "operationId": "ruleServiceErrorStatusGet",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "description": "サービスID。取得対象スマートデバイス",
                        "required": true,
                        "type": "string"
                    }, 
                    {
                        "name": "ruleServiceId",
                        "in": "query",
                        "description": "ルールを識別するためのサービスID。<br>省略時は全てのルールが取得対象。",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/RuleServiceGetErrorStatusResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "errors": [
                                    {
                                        "ruleServiceId": "ruleService20170101123456",
                                        "errorStatus": "Request Timeout.",
                                        "errorTimestamp": "2018-01-01T00:00:00+0900"
                                    }
                                ]
                            }
                        }
                    }
                },
                "x-type": "one-shot"
            },
            "put": {
                "summary": "設定されているルールサービスのエラー発生監視を開始する。",
                "description": "",
                "operationId": "ruleServiceErrorStatusPut",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "description": "サービスID。取得対象スマートデバイス",
                        "required": true,
                        "type": "string"
                    }, 
                    {
                        "name": "ruleServiceId",
                        "in": "query",
                        "description": "ルールを識別するためのサービスID。<br>省略時は全てのルールが取得対象。",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventRegistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "ruleServiceId": "ruleService20170101123456",
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                },
                "x-type": "event",
                "x-event": {
                    "schema": {
                        "$ref": "#/definitions/ErrorStatusEvent"
                    },
                    "examples": {
                        "application/json": {
                            "serviceId": "ruleService20170101123456",
                            "profile": "ruleservice",
                            "attribute": "errorstatus",
                            "errors": [
                                {
                                    "ruleServiceId": "ruleService20170101123456",
                                    "errorStatus": "Request Timeout.",
                                    "errorTimestamp": "2018-01-01T00:00:00+0900"
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "summary": "設定されているルールサービスのエラー発生監視を終了する。",
                "description": "",
                "operationId": "ruleServiceErrorStatusDelete",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "description": "サービスID。取得対象スマートデバイス",
                        "required": true,
                        "type": "string"
                    }, 
                    {
                        "name": "ruleServiceId",
                        "in": "query",
                        "description": "ルールを識別するためのサービスID。<br>省略時は全てのルールが取得対象。",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/EventUnregistrationResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                },
                "x-type": "event"
            }
        }
    },
    "definitions": {
        "Rules": {
            "type": "object",
            "required": ["errorStatus", "ruleEnable", "ruleServiceId", "ruleServiceType"],
            "properties": {
                "ruleServiceId": {
                    "type": "string",
                    "description": "設定されたルールを識別するためのserviceId。",
                    "title": "ルール serviceId"
                },
                "ruleServiceType": {
                    "type": "string",
                    "description": "ルールサービスタイプ。",
                    "title": "ルールサービスタイプ",
                    "enum": ["rule", "and"]
                },
                "ruleEnable": {
                    "type": "boolean",
                    "description": "ルールの有効／無効。",
                    "title": "ルール動作状態"
                },
                "errorStatus": {
                    "type": "string",
                    "description": "エラー発生状況。",
                    "title": "エラーステータス"
                },
                "errorTimestamp": {
                    "type": "string",
                    "description": "エラー発生時の時刻情報 (RFC3339)。",
                    "title": "エラー発生時刻"
                },
                "Triggers": {
                    "type": "object",
                    "description": "トリガー条件。",
                    "title": "トリガー条件",
                    "properties": {
                        "triggerInterval": {
                            "type": "number",
                            "description": "トリガー条件のRESTを実行する間隔<br>省略時はルール開始後即発動。",
                            "title": "トリガーインターバル"
                        },
                        "triggerIntervalUnit": {
                            "type": "string",
                            "description": "トリガーインターバルの単位。",
                            "title": "トリガーインターバル単位"
                        },
                        "trigger": {
                            "type": "string",
                            "description": "トリガー条件を取得するサービスをREST URIにて記載<br>「Date&Time」記述時はDate&Time設定として動作。",
                            "title": "トリガー条件"
                        },
                        "triggerActioin": {
                            "type": "string",
                            "description": "トリガー条件RESTのアクション。",
                            "title": "トリガーアクション",
                            "enum": ["GET", "POST", "PUT", "DELETE"]
                        },
                        "triggerParameter": {
                            "type": "string",
                            "description": "トリガー条件RESTのパラメータ。",
                            "title": "トリガーパラメータ"
                        },
                        "comparisonLeft": {
                            "type": "string",
                            "description": "比較条件の左辺に該当する値。",
                            "title": "比較値 (左辺)"
                        },
                        "comparisonLeftDataType": {
                            "type": "string",
                            "description": "比較条件の左辺に該当する値のデータタイプ。",
                            "title": "比較値 (左辺)のデータタイプ"
                        },
                        "comparison": {
                            "type": "string",
                            "description": "トリガー条件比較演算子<br>省略時はトリガー条件取得後即時被悪条件成立と判断。",
                            "title": "比較条件"
                        },
                        "comparisonRight": {
                            "type": "string",
                            "description": "比較条件の右辺に該当する値。",
                            "title": "比較値 (右辺)"
                        },
                        "comparisonRightDataType": {
                            "type": "string",
                            "description": "比較条件の右辺に該当する値のデータタイプ。",
                            "title": "比較値 (右辺)のデータタイプ"
                        }
                    },
                    "required": ["trigger"]
                },
                "Operations": {
                    "type": "object",
                    "description": "オペレーション。",
                    "title": "オペレーション",
                    "properties": {
                        "operationIndex": {
                            "type": "number",
                            "description": "オペレーションインデックス。",
                            "title": "オペレーションインデックス"
                        },
                        "operation": {
                            "type": "string",
                            "description": "トリガー条件成立時のオペレーションREST URI。",
                            "title": "オペレーション"
                        },
                        "operationAction": {
                            "type": "string",
                            "description": "オペレーション条件RESTのアクション。",
                            "title": "オペレーションアクション",
                            "enum": ["GET", "POST", "PUT", "DELETE"]
                        },
                        "operationParameter": {
                            "type": "string",
                            "description": "オペレーション条件RESTのパラメータ。",
                            "title": "オペレーションパラメータ"
                        },
                        "delayOccurrence": {
                            "type": "string",
                            "description": "オペレーション実行中に新たに実行要求が行われた場合の処理対応設定。",
                            "title": "処理遅延発生時の次回処理",
                            "enum": ["skip", "stack"]
                        }
                    }
                }
            }
        },
        "RuleServiceGetListResponse": {
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }, 
                {
                    "$ref": "#/definitions/Rules"
                }
            ]
        },
        "CreateResponse": {
            "type": "object",
            "required": ["ruleServiceId"],
            "properties": {
                "ruleServiceId": {
                    "type": "string",
                    "description": "ルールを識別するためのserviceId。",
                    "title": "ルール serviceId"
                }
            }
        },
        "RuleServiceCreateResponse": {
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }, 
                {
                    "$ref": "#/definitions/CreateResponse"
                }
            ]
        },
        "RuleServiceDeleteResponse": {
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }
            ]
        },
        "RuleServiceGetErrorStatusResponse": {
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }, 
                {
                    "$ref": "#/definitions/ErrorStatusInfo"
                }
            ]
        },
        "ErrorStatusInfo": {
            "type": "object",
            "required": ["errors"],
            "properties": {
                "errors": {
                    "type": "object",
                    "title": "エラー一覧",
                    "properties": {
                        "ruleServiceId": {
                            "type": "string",
                            "description": "エラーが発生しているルールを識別するためのserviceId。",
                            "title": "ルール serviceId"
                        },
                        "errorStatus": {
                            "type": "string",
                            "description": "エラー発生状況。",
                            "title": "エラーステータス"
                        },
                        "errorTimestamp": {
                            "type": "string",
                            "description": "エラー発生時の時刻情報 (RFC3339)。",
                            "title": "エラー発生時刻"
                        }
                    },
                    "required": ["errorStatus", "errorTimestamp", "ruleServiceId"]
                }
            }
        },
        "ErrorStatusEvent": {
            "allOf": [
                {
                    "$ref": "#/definitions/CommonEvent"
                }, 
                {
                    "$ref": "#/definitions/ErrorStatusInfo"
                }
            ]
        },
        "CommonResponse": {
            "type": "object",
            "required": ["product", "result", "version"],
            "properties": {
                "result": {
                    "type": "integer",
                    "description": "0: 正常応答<br>0以外: 異常応答",
                    "title": "処理結果"
                },
                "product": {
                    "type": "string",
                    "description": "DeviceConnectシステムの名前。",
                    "title": "システム名"
                },
                "version": {
                    "type": "string",
                    "description": "DeviceConnectシステムのバージョン名。",
                    "title": "システムバージョン"
                },
                "hmac": {
                    "type": "string",
                    "description": "レスポンスに対する署名。アプリケーション側から事前にHMACキーを共有されていた場合は必須。",
                    "title": "署名"
                }
            }
        },
        "EventRegistrationResponse": {
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }
            ]
        },
        "EventUnregistrationResponse": {
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }
            ]
        },
        "CommonEvent": {
            "type": "object",
            "required": ["attribute", "interface", "profile", "serviceId"],
            "properties": {
                "serviceId": {
                    "type": "string",
                    "description": "イベントを送信したサービスのID",
                    "title": "サービスID"
                },
                "profile": {
                    "type": "string",
                    "description": "プロファイル名。",
                    "title": "プロファイル名"
                },
                "interface": {
                    "type": "string",
                    "description": "インターフェース名。",
                    "title": "インターフェース名"
                },
                "attribute": {
                    "type": "string",
                    "description": "アトリビュート名。",
                    "title": "アトリビュート名"
                }
            }
        }
    }
}