
{
    "swagger": "2.0",
    "info": {
        "description": "Tag (NFC、QRなど) の機能を提供するAPI。",
        "version": "1.0.0",
        "title": "Tag Profile"
    },
    "basePath": "/gotapi/tag",
    "consumes": ["application/x-www-form-urlencoded", "multipart/form-data"],
    "paths": {
        "/": {
            "get": {
                "summary": "Tag の情報を読み込みます。",
                "description": "",
                "operationId": "tagGet",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "description": "サービスID。<br>取得対象デバイスを示すIDになります。",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "uri",
                        "in": "query",
                        "description": "画像リソースへのURI。<br>QR コードなどのタグが含まれる画像へのURIを指定することで解析することができます。<br><br>NFC などの画像リソースを使用しないタグでは無視されます。",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/GetTagResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "tags": [
                                    {
                                        "text": "NFC,QRのデータ"
                                    }
                                ]
                            }
                        }
                    }
                },
                "x-type": "one-shot"
            },
            "post": {
                "summary": "Tag にデータを書き込みます。",
                "description": "Tag (NFC、QRなど) にデータを書き込みます。",
                "operationId": "tagPost",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "description": "サービスID。<br>取得対象デバイスを示すIDになります。",
                        "required": true,
                        "type": "string"
                    }, 
                    {
                        "name": "languageCode",
                        "in": "formData",
                        "description": "Tag に書き込むテキストの言語コード。<br>タグにtextを書き込む時に言語コードが必要な場合にしてします。<br>指定されていない場合にはデフォルトでenが指定されます。",
                        "required": false,
                        "type": "string"
                    }, 
                    {
                        "name": "text",
                        "in": "formData",
                        "description": "Tag に書き込むテキスト。<br>text、uri のどちらかを指定する必要があります。",
                        "required": false,
                        "type": "string"
                    }, 
                    {
                        "name": "uri",
                        "in": "formData",
                        "description": "Tag に書き込むURI。<br> textが指定されている場合には、textを優先します。<br>text、uri のどちらかを指定する必要があります。",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/PostTagResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0",
                                "uri": "http://localhost:9999/qr.jpeg"
                            }
                        }
                    }
                },
                "x-type": "one-shot"
            }
        },
        "/onRead": {
            "put": {
                "summary": "Tag を読み込んだ時のイベントを登録します。",
                "description": "NFC、QR などのタグを読み込んだ時にイベントでテキストを通知します。",
                "operationId": "tagOnReadPut",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "formData",
                        "description": "サービスID。<br>取得対象デバイスを示すIDになります。",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/TagOnReadResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                },
                "x-type": "event",
                "x-event": {
                    "schema": {
                        "$ref": "#/definitions/TagOnReadEvent"
                    },
                    "examples": {
                        "application/json": {
                            "serviceId": "tag.dummyId.localhost.deviceconnect.org",
                            "profile": "tag",
                            "attribute": "onRead",
                            "tags": [
                                {
                                    "text": "NFC, QR に格納されていたテキスト"
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "summary": "Tagの読み込みイベントを解除します。",
                "description": "",
                "operationId": "tagOnReadDelete",
                "parameters": [
                    {
                        "name": "serviceId",
                        "in": "query",
                        "description": "サービスID。<br>取得対象デバイスを示すIDになります。",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/CommonResponse"
                        },
                        "examples": {
                            "application/json": {
                                "result": 0,
                                "product": "Example System",
                                "version": "1.0.0"
                            }
                        }
                    }
                },
                "x-type": "event"
            }
        }
    },
    "definitions": {
        "CommonResponse": {
            "type": "object",
            "required": ["product", "result", "version"],
            "properties": {
                "result": {
                    "type": "integer",
                    "description": "0: 正常応答<br>0以外: 異常応答",
                    "title": "処理結果"
                },
                "product": {
                    "type": "string",
                    "description": "DeviceConnect システムの名前。",
                    "title": "DeviceConnect システムの名前"
                },
                "version": {
                    "type": "string",
                    "description": "DeviceConnect システムのバージョン名。",
                    "title": "DeviceConnect システムのバージョン名"
                },
                "hmac": {
                    "type": "string",
                    "description": "レスポンスに対する署名。<br>アプリケーション側から事前にHMACキーを共有されていた場合は必須。",
                    "title": "署名"
                }
            }
        },
        "PostTagResponse": {
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }, 
                {
                    "type": "object",
                    "properties": {
                        "uri": {
                            "type": "string",
                            "description": "画像リソースへのURI。<br><br>画像リソースが無い場合には省略されます。",
                            "title": "画像リソースへのURI"
                        }
                    }
                }
            ]
        },
        "GetTagResponse": {
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }, 
                {
                    "$ref": "#/definitions/TagList"
                }
            ]
        },
        "TagOnReadResponse": {
            "allOf": [
                {
                    "$ref": "#/definitions/CommonResponse"
                }
            ]
        },
        "TagOnReadEvent": {
            "allOf": [
                {
                    "$ref": "#/definitions/CommonEvent"
                }, 
                {
                    "$ref": "#/definitions/TagList"
                }
            ]
        },
        "TagList": {
            "type": "object",
            "required": ["tags"],
            "properties": {
                "tags": {
                    "type": "array",
                    "description": "タグ情報を格納する配列。<br>タグ情報の中身には、タグによって異なります。",
                    "title": "タグ情報を格納する配列。",
                    "items": {
                        "$ref": "#/definitions/TagInfo"
                    }
                }
            }
        },
        "TagInfo": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string",
                    "description": "Tag (NFC, QR) に格納されていたテキスト。",
                    "title": "Tag (NFC, QR) に格納されていたテキスト"
                },
                "languageCode": {
                    "type": "string",
                    "description": "Tag (NFC, QR) に格納されていたテキストの言語コード。",
                    "title": "Tag (NFC, QR) に格納されていたテキストの言語コード"
                },
                "uri": {
                    "type": "string",
                    "description": "Tag (NFC, QR) に格納されていたURI。",
                    "title": "Tag (NFC, QR) に格納されていたURI"
                }
            }
        },
        "CommonEvent": {
            "type": "object",
            "required": ["attribute", "interface", "profile", "serviceId"],
            "properties": {
                "serviceId": {
                    "type": "string",
                    "description": "イベントを送信したサービスのID。",
                    "title": "サービスID"
                },
                "profile": {
                    "type": "string",
                    "description": "プロファイル名。",
                    "title": "プロファイル名"
                },
                "interface": {
                    "type": "string",
                    "description": "インターフェース名。",
                    "title": "インターフェース名"
                },
                "attribute": {
                    "type": "string",
                    "description": "アトリビュート名。",
                    "title": "アトリビュート名"
                }
            }
        }
    }
}